"""empty message

Revision ID: 825d5e10b106
Revises: 
Create Date: 2018-06-06 13:47:22.256348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825d5e10b106'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('rating_numbering', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'rating_numbering')
    # ### end Alembic commands ###
